language: scala

scala:
    - 2.11.4

jdk:
    - oraclejdk8

addons:
    postgresql: "9.3"

before_script:
    - bash bin/bootstrap_database.bash

script: sbt coverage test

# go faster on travis
sudo: false

notifications:
    email:
        - eric.bowman@zalando.de
        - valentine.gogichashvili@zalando.de
        - alexander.kukushkin@zalando.de

