language: scala
scala:
    - 2.11.4
jdk:
    - oraclejdk8
addons:
    postgresql: "9.3"
before_script:
    - bash test/bootstrap_database.sh
    - pushd test/database
    - exit 1
    - popd

# go faster on travis
sudo: false
